[project]
name = "docutranslate"
version = "0.0.6"
description = "能翻译pdf和markdown的软件"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docling>=2.31.0",
    "httpx>=0.28.1",
    "markdown2>=2.5.3",
    "transformers>=4.42.4",
]
