[project]
name = "docutranslate"
version = "0.2.22"
description = "文件翻译工具"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "markdown2",
    "fastapi[standard]>=0.115.12",
    "pyinstaller>=6.13.0",
]
[project.scripts]
docutranslate = "docutranslate.cli:main"

[build-system]
requires = ["setuptools>=61.0"] # 或者你需要的 setuptools 版本
build-backend = "setuptools.build_meta"
backend-path = ["."]
[tool.setuptools.package-data]
docutranslate = ["static/**"]
